steps:
  # Paso 1: Construir la imagen Docker desde el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/big-moments-gcp', '.']

  # Paso 2: Empujar la imagen Docker a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/big-moments-gcp']

images:
  - 'gcr.io/$PROJECT_ID/big-moments-gcp'

options:
logging: CLOUD_LOGGING_ONLY
logs_bucket: 'gs://visionbucketg1'

