steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/big-moments-gcp', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/big-moments-gcp']

images:
  - 'gcr.io/$PROJECT_ID/big-moments-gcp'

options:
  logs_bucket: gs://visionbucketg1 
